[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "satellite-image-analyzer"
version = "0.1.0"
description = "Satellite Image Analyzer project using flood fill and grid algorithms"
authors = [
  { name="Emmanuel Acheampng", email="acheampe@oregonstate.edu" }
]
dependencies = []

[project.optional-dependencies]
dev = ["pytest"]

[tool.setuptools.packages.find]
where = ["src"]

[tool.pytest.ini_options]
addopts = "--cov=src/gridtools --cov-report=term-missing"
testpaths = [
    "tests",
]